name: CI

on:
  push:
    branches:
      - main
      - "**"
  pull_request:
    branches:
      - main

jobs:
  preprocessor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Test Preprocessor
        run: sbt "testOnly *preprocessorTest"

  expander:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Test Expander
        run: sbt "testOnly *ExpanderTest"

  compressor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Test Compressor
        run: sbt "testOnly *compressorTest"

  sha256:
    needs:
      - preprocessor
      - expander
      - compressor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Test Sha256 core
        run: sbt "testOnly *sha256Test"
